resources:
- allow-argocd-to-manage.yaml
- https://github.com/redhat-appstudio/application-service/config/default?ref=7861066f76f46825b2b84c669c67a5cb6742b65c
- .tekton/


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/application-service
  newName: quay.io/redhat-appstudio/application-service
  newTag: 7861066f76f46825b2b84c669c67a5cb6742b65c

configMapGenerator:
- literals:
  - GITHUB_ORG=""
  name: github-config
  behavior: replace

namespace: application-service

patches:
  - ./manager_resources_patch.yaml
